/**************************************************************************
 * The MIT License                                                        *
 * Copyright (c) 2011 Antony Arciuolo & Kevin Myers                       *
 *                                                                        *
 * Permission is hereby granted, free of charge, to any person obtaining  *
 * a copy of this software and associated documentation files (the        *
 * "Software"), to deal in the Software without restriction, including    *
 * without limitation the rights to use, copy, modify, merge, publish,    *
 * distribute, sublicense, and/or sell copies of the Software, and to     *
 * permit persons to whom the Software is furnished to do so, subject to  *
 * the following conditions:                                              *
 *                                                                        *
 * The above copyright notice and this permission notice shall be         *
 * included in all copies or substantial portions of the Software.        *
 *                                                                        *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,        *
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF     *
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND                  *
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE *
 * LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION *
 * OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION  *
 * WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.        *
 **************************************************************************/
#pragma once
#ifndef oDescUtil_h
#define oDescUtil_h

// In the oooii lib a common pattern is to have a majority of the data of a class as a DESC
// object in the style of DirectX and much of Win32 API. Since DESC is mostly POD config-type
// data, it is often useful to convert it to string for various purposes, so here are some 
// helper functions.

// _____________________________________________________________________________
// Internal implementation macros (don't call)

#define oPRINTF_BEGIN__(_StrInstanceName) do { printf("%s\n", _StrInstanceName); char buf[128];
#define oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, _FieldName) oToString(buf, (_Struct)._FieldName); _PerLinePreCmd; printf("  %s: %s\n", #_FieldName, buf);
#define oPRINTF_END__() } while(false)

#define oREADINI_BEGIN__() do {
#define oREADINI_FIELDOP__(_INI, _hSection, _Struct, _FieldName) oFromString(&(_Struct)._FieldName, (_INI).GetValue(_hSection, #_FieldName));
#define oREADINI_END__() } while(false)

#define oENUM_FROM_STRING_BEGIN__( type ) errno_t oFromString( type* _value, const char* _string ){ if( false ){}
#define oENUM_FROM_STRING_SLOT__( namespace, value ) else if( _stricmp( _string, #value ) == 0 ) *_value = namespace::value;
#define oENUM_FROM_STRING_END__() return 0; }

// _____________________________________________________________________________
// Public macros

#define oPRINTF_FIELDS1(_Struct, _StrInstanceName, _PerLinePreCmd, a) oPRINTF_BEGIN__(_StrInstanceName) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, a) oPRINTF_END__()
#define oPRINTF_FIELDS2(_Struct, _StrInstanceName, _PerLinePreCmd, a, b) oPRINTF_BEGIN__(_StrInstanceName) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, a) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, b) oPRINTF_END__()
#define oPRINTF_FIELDS3(_Struct, _StrInstanceName, _PerLinePreCmd, a, b, c) oPRINTF_BEGIN__(_StrInstanceName) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, a) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, b) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, c) oPRINTF_END__()
#define oPRINTF_FIELDS4(_Struct, _StrInstanceName, _PerLinePreCmd, a, b, c, d) oPRINTF_BEGIN__(_StrInstanceName) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, a) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, b) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, c) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, d) oPRINTF_END__()
#define oPRINTF_FIELDS5(_Struct, _StrInstanceName, _PerLinePreCmd, a, b, c, d, e) oPRINTF_BEGIN__(_StrInstanceName) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, a) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, b) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, c) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, d) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, e) oPRINTF_END__()
#define oPRINTF_FIELDS6(_Struct, _StrInstanceName, _PerLinePreCmd, a, b, c, d, e, f) oPRINTF_BEGIN__(_StrInstanceName) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, a) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, b) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, c) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, d) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, e) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, f) oPRINTF_END__()
#define oPRINTF_FIELDS7(_Struct, _StrInstanceName, _PerLinePreCmd, a, b, c, d, e, f, g) oPRINTF_BEGIN__(_StrInstanceName) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, a) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, b) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, c) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, d) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, e) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, f) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, g) oPRINTF_END__()
#define oPRINTF_FIELDS8(_Struct, _StrInstanceName, _PerLinePreCmd, a, b, c, d, e, f, g, h) oPRINTF_BEGIN__(_StrInstanceName) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, a) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, b) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, c) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, d) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, e) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, f) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, g) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, h) oPRINTF_END__()
#define oPRINTF_FIELDS9(_Struct, _StrInstanceName, _PerLinePreCmd, a, b, c, d, e, f, g, h, i) oPRINTF_BEGIN__(_StrInstanceName) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, a) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, b) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, c) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, d) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, e) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, f) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, g) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, h) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, i) oPRINTF_END__()
#define oPRINTF_FIELDS10(_Struct, _StrInstanceName, _PerLinePreCmd, a, b, c, d, e, f, g, h, i, j) oPRINTF_BEGIN__(_StrInstanceName) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, a) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, b) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, c) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, d) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, e) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, f) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, g) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, h) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, i) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, j) oPRINTF_END__()
#define oPRINTF_FIELDS11(_Struct, _StrInstanceName, _PerLinePreCmd, a, b, c, d, e, f, g, h, i, j, k) oPRINTF_BEGIN__(_StrInstanceName) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, a) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, b) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, c) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, d) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, e) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, f) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, g) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, h) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, i) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, j) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, k) oPRINTF_END__()
#define oPRINTF_FIELDS12(_Struct, _StrInstanceName, _PerLinePreCmd, a, b, c, d, e, f, g, h, i, j, k, l) oPRINTF_BEGIN__(_StrInstanceName) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, a) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, b) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, c) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, d) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, e) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, f) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, g) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, h) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, i) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, j) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, k) oPRINTF_FIELDOP__(_PerLinePreCmd, _Struct, l) oPRINTF_END__()

#define oREADINI1(_Struct, _INI, _hSection, a) oREADINI_BEGIN__() oREADINI_FIELDOP__(_INI, _hSection, _Struct, a) oREADINI_END__()
#define oREADINI2(_Struct, _INI, _hSection, a, b) oREADINI_BEGIN__() oREADINI_FIELDOP__(_INI, _hSection, _Struct, a) oREADINI_FIELDOP__(_INI, _hSection, _Struct, b) oREADINI_END__()
#define oREADINI3(_Struct, _INI, _hSection, a, b, c) oREADINI_BEGIN__() oREADINI_FIELDOP__(_INI, _hSection, _Struct, a) oREADINI_FIELDOP__(_INI, _hSection, _Struct, b) oREADINI_FIELDOP__(_INI, _hSection, _Struct, c) oREADINI_END__()
#define oREADINI4(_Struct, _INI, _hSection, a, b, c, d) oREADINI_BEGIN__() oREADINI_FIELDOP__(_INI, _hSection, _Struct, a) oREADINI_FIELDOP__(_INI, _hSection, _Struct, b) oREADINI_FIELDOP__(_INI, _hSection, _Struct, c) oREADINI_FIELDOP__(_INI, _hSection, _Struct, d) oREADINI_END__()
#define oREADINI5(_Struct, _INI, _hSection, a, b, c, d, e) oREADINI_BEGIN__() oREADINI_FIELDOP__(_INI, _hSection, _Struct, a) oREADINI_FIELDOP__(_INI, _hSection, _Struct, b) oREADINI_FIELDOP__(_INI, _hSection, _Struct, c) oREADINI_FIELDOP__(_INI, _hSection, _Struct, d) oREADINI_FIELDOP__(_INI, _hSection, _Struct, e) oREADINI_END__()
#define oREADINI6(_Struct, _INI, _hSection, a, b, c, d, e, f) oREADINI_BEGIN__() oREADINI_FIELDOP__(_INI, _hSection, _Struct, a) oREADINI_FIELDOP__(_INI, _hSection, _Struct, b) oREADINI_FIELDOP__(_INI, _hSection, _Struct, c) oREADINI_FIELDOP__(_INI, _hSection, _Struct, d) oREADINI_FIELDOP__(_INI, _hSection, _Struct, e) oREADINI_FIELDOP__(_INI, _hSection, _Struct, f) oREADINI_END__()
#define oREADINI7(_Struct, _INI, _hSection, a, b, c, d, e, f, g) oREADINI_BEGIN__() oREADINI_FIELDOP__(_INI, _hSection, _Struct, a) oREADINI_FIELDOP__(_INI, _hSection, _Struct, b) oREADINI_FIELDOP__(_INI, _hSection, _Struct, c) oREADINI_FIELDOP__(_INI, _hSection, _Struct, d) oREADINI_FIELDOP__(_INI, _hSection, _Struct, e) oREADINI_FIELDOP__(_INI, _hSection, _Struct, f) oREADINI_FIELDOP__(_INI, _hSection, _Struct, g) oREADINI_END__()
#define oREADINI8(_Struct, _INI, _hSection, a, b, c, d, e, f, g, h) oREADINI_BEGIN__() oREADINI_FIELDOP__(_INI, _hSection, _Struct, a) oREADINI_FIELDOP__(_INI, _hSection, _Struct, b) oREADINI_FIELDOP__(_INI, _hSection, _Struct, c) oREADINI_FIELDOP__(_INI, _hSection, _Struct, d) oREADINI_FIELDOP__(_INI, _hSection, _Struct, e) oREADINI_FIELDOP__(_INI, _hSection, _Struct, f) oREADINI_FIELDOP__(_INI, _hSection, _Struct, g) oREADINI_FIELDOP__(_INI, _hSection, _Struct, h) oREADINI_END__()
#define oREADINI9(_Struct, _INI, _hSection, a, b, c, d, e, f, g, h, i) oREADINI_BEGIN__() oREADINI_FIELDOP__(_INI, _hSection, _Struct, a) oREADINI_FIELDOP__(_INI, _hSection, _Struct, b) oREADINI_FIELDOP__(_INI, _hSection, _Struct, c) oREADINI_FIELDOP__(_INI, _hSection, _Struct, d) oREADINI_FIELDOP__(_INI, _hSection, _Struct, e) oREADINI_FIELDOP__(_INI, _hSection, _Struct, f) oREADINI_FIELDOP__(_INI, _hSection, _Struct, g) oREADINI_FIELDOP__(_INI, _hSection, _Struct, h) oREADINI_FIELDOP__(_INI, _hSection, _Struct, i) oREADINI_END__()
#define oREADINI10(_Struct, _INI, _hSection, a, b, c, d, e, f, g, h, i, j) oREADINI_BEGIN__() oREADINI_FIELDOP__(_INI, _hSection, _Struct, a) oREADINI_FIELDOP__(_INI, _hSection, _Struct, b) oREADINI_FIELDOP__(_INI, _hSection, _Struct, c) oREADINI_FIELDOP__(_INI, _hSection, _Struct, d) oREADINI_FIELDOP__(_INI, _hSection, _Struct, e) oREADINI_FIELDOP__(_INI, _hSection, _Struct, f) oREADINI_FIELDOP__(_INI, _hSection, _Struct, g) oREADINI_FIELDOP__(_INI, _hSection, _Struct, h) oREADINI_FIELDOP__(_INI, _hSection, _Struct, i) oREADINI_FIELDOP__(_INI, _hSection, _Struct, j) oREADINI_END__()
#define oREADINI11(_Struct, _INI, _hSection, a, b, c, d, e, f, g, h, i, j, k) oREADINI_BEGIN__() oREADINI_FIELDOP__(_INI, _hSection, _Struct, a) oREADINI_FIELDOP__(_INI, _hSection, _Struct, b) oREADINI_FIELDOP__(_INI, _hSection, _Struct, c) oREADINI_FIELDOP__(_INI, _hSection, _Struct, d) oREADINI_FIELDOP__(_INI, _hSection, _Struct, e) oREADINI_FIELDOP__(_INI, _hSection, _Struct, f) oREADINI_FIELDOP__(_INI, _hSection, _Struct, g) oREADINI_FIELDOP__(_INI, _hSection, _Struct, h) oREADINI_FIELDOP__(_INI, _hSection, _Struct, i) oREADINI_FIELDOP__(_INI, _hSection, _Struct, j) oREADINI_FIELDOP__(_INI, _hSection, _Struct, k) oREADINI_END__()
#define oREADINI12(_Struct, _INI, _hSection, a, b, c, d, e, f, g, h, i, j, k, l) oREADINI_BEGIN__() oREADINI_FIELDOP__(_INI, _hSection, _Struct, a) oREADINI_FIELDOP__(_INI, _hSection, _Struct, b) oREADINI_FIELDOP__(_INI, _hSection, _Struct, c) oREADINI_FIELDOP__(_INI, _hSection, _Struct, d) oREADINI_FIELDOP__(_INI, _hSection, _Struct, e) oREADINI_FIELDOP__(_INI, _hSection, _Struct, f) oREADINI_FIELDOP__(_INI, _hSection, _Struct, g) oREADINI_FIELDOP__(_INI, _hSection, _Struct, h) oREADINI_FIELDOP__(_INI, _hSection, _Struct, i) oREADINI_FIELDOP__(_INI, _hSection, _Struct, j) oREADINI_FIELDOP__(_INI, _hSection, _Struct, k) oREADINI_FIELDOP__(_INI, _hSection, _Struct, l) oREADINI_END__()
#define oREADINI13(_Struct, _INI, _hSection, a, b, c, d, e, f, g, h, i, j, k, l, m) oREADINI_BEGIN__() oREADINI_FIELDOP__(_INI, _hSection, _Struct, a) oREADINI_FIELDOP__(_INI, _hSection, _Struct, b) oREADINI_FIELDOP__(_INI, _hSection, _Struct, c) oREADINI_FIELDOP__(_INI, _hSection, _Struct, d) oREADINI_FIELDOP__(_INI, _hSection, _Struct, e) oREADINI_FIELDOP__(_INI, _hSection, _Struct, f) oREADINI_FIELDOP__(_INI, _hSection, _Struct, g) oREADINI_FIELDOP__(_INI, _hSection, _Struct, h) oREADINI_FIELDOP__(_INI, _hSection, _Struct, i) oREADINI_FIELDOP__(_INI, _hSection, _Struct, j) oREADINI_FIELDOP__(_INI, _hSection, _Struct, k) oREADINI_FIELDOP__(_INI, _hSection, _Struct, l) oREADINI_FIELDOP__(_INI, _hSection, _Struct, m) oREADINI_END__()
#define oREADINI14(_Struct, _INI, _hSection, a, b, c, d, e, f, g, h, i, j, k, l, m, n) oREADINI_BEGIN__() oREADINI_FIELDOP__(_INI, _hSection, _Struct, a) oREADINI_FIELDOP__(_INI, _hSection, _Struct, b) oREADINI_FIELDOP__(_INI, _hSection, _Struct, c) oREADINI_FIELDOP__(_INI, _hSection, _Struct, d) oREADINI_FIELDOP__(_INI, _hSection, _Struct, e) oREADINI_FIELDOP__(_INI, _hSection, _Struct, f) oREADINI_FIELDOP__(_INI, _hSection, _Struct, g) oREADINI_FIELDOP__(_INI, _hSection, _Struct, h) oREADINI_FIELDOP__(_INI, _hSection, _Struct, i) oREADINI_FIELDOP__(_INI, _hSection, _Struct, j) oREADINI_FIELDOP__(_INI, _hSection, _Struct, k) oREADINI_FIELDOP__(_INI, _hSection, _Struct, l) oREADINI_FIELDOP__(_INI, _hSection, _Struct, m) oREADINI_FIELDOP__(_INI, _hSection, _Struct, n) oREADINI_END__()
#define oREADINI15(_Struct, _INI, _hSection, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) oREADINI_BEGIN__() oREADINI_FIELDOP__(_INI, _hSection, _Struct, a) oREADINI_FIELDOP__(_INI, _hSection, _Struct, b) oREADINI_FIELDOP__(_INI, _hSection, _Struct, c) oREADINI_FIELDOP__(_INI, _hSection, _Struct, d) oREADINI_FIELDOP__(_INI, _hSection, _Struct, e) oREADINI_FIELDOP__(_INI, _hSection, _Struct, f) oREADINI_FIELDOP__(_INI, _hSection, _Struct, g) oREADINI_FIELDOP__(_INI, _hSection, _Struct, h) oREADINI_FIELDOP__(_INI, _hSection, _Struct, i) oREADINI_FIELDOP__(_INI, _hSection, _Struct, j) oREADINI_FIELDOP__(_INI, _hSection, _Struct, k) oREADINI_FIELDOP__(_INI, _hSection, _Struct, l) oREADINI_FIELDOP__(_INI, _hSection, _Struct, m) oREADINI_FIELDOP__(_INI, _hSection, _Struct, n) oREADINI_FIELDOP__(_INI, _hSection, _Struct, o) oREADINI_END__()
#define oREADINI16(_Struct, _INI, _hSection, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) oREADINI_BEGIN__() oREADINI_FIELDOP__(_INI, _hSection, _Struct, a) oREADINI_FIELDOP__(_INI, _hSection, _Struct, b) oREADINI_FIELDOP__(_INI, _hSection, _Struct, c) oREADINI_FIELDOP__(_INI, _hSection, _Struct, d) oREADINI_FIELDOP__(_INI, _hSection, _Struct, e) oREADINI_FIELDOP__(_INI, _hSection, _Struct, f) oREADINI_FIELDOP__(_INI, _hSection, _Struct, g) oREADINI_FIELDOP__(_INI, _hSection, _Struct, h) oREADINI_FIELDOP__(_INI, _hSection, _Struct, i) oREADINI_FIELDOP__(_INI, _hSection, _Struct, j) oREADINI_FIELDOP__(_INI, _hSection, _Struct, k) oREADINI_FIELDOP__(_INI, _hSection, _Struct, l) oREADINI_FIELDOP__(_INI, _hSection, _Struct, m) oREADINI_FIELDOP__(_INI, _hSection, _Struct, n) oREADINI_FIELDOP__(_INI, _hSection, _Struct, o) oREADINI_FIELDOP__(_INI, _hSection, _Struct, p) oREADINI_END__()

#define oENUM_STRING1( enum, namespace, a )                            oENUM_FROM_STRING_BEGIN__( enum ) oENUM_FROM_STRING_SLOT__( namespace, a ) oENUM_FROM_STRING_END__()
#define oENUM_STRING2( enum, namespace, a, b )                         oENUM_FROM_STRING_BEGIN__( enum ) oENUM_FROM_STRING_SLOT__( namespace, a ) oENUM_FROM_STRING_SLOT__( namespace, b ) oENUM_FROM_STRING_END__()
#define oENUM_STRING3( enum, namespace, a, b, c )                      oENUM_FROM_STRING_BEGIN__( enum ) oENUM_FROM_STRING_SLOT__( namespace, a ) oENUM_FROM_STRING_SLOT__( namespace, b ) oENUM_FROM_STRING_SLOT__( namespace, c ) oENUM_FROM_STRING_END__()
#define oENUM_STRING4( enum, namespace, a, b, c, d )                   oENUM_FROM_STRING_BEGIN__( enum ) oENUM_FROM_STRING_SLOT__( namespace, a ) oENUM_FROM_STRING_SLOT__( namespace, b ) oENUM_FROM_STRING_SLOT__( namespace, c ) oENUM_FROM_STRING_SLOT__( namespace, d ) oENUM_FROM_STRING_END__()
#define oENUM_STRING5( enum, namespace, a, b, c, d, e )                oENUM_FROM_STRING_BEGIN__( enum ) oENUM_FROM_STRING_SLOT__( namespace, a ) oENUM_FROM_STRING_SLOT__( namespace, b ) oENUM_FROM_STRING_SLOT__( namespace, c ) oENUM_FROM_STRING_SLOT__( namespace, d ) oENUM_FROM_STRING_SLOT__( namespace, e ) oENUM_FROM_STRING_END__()
#define oENUM_STRING6( enum, namespace, a, b, c, d, e, f )             oENUM_FROM_STRING_BEGIN__( enum ) oENUM_FROM_STRING_SLOT__( namespace, a ) oENUM_FROM_STRING_SLOT__( namespace, b ) oENUM_FROM_STRING_SLOT__( namespace, c ) oENUM_FROM_STRING_SLOT__( namespace, d ) oENUM_FROM_STRING_SLOT__( namespace, e ) oENUM_FROM_STRING_SLOT__( namespace, f ) oENUM_FROM_STRING_END__()
#define oENUM_STRING7( enum, namespace, a, b, c, d, e, f, g )          oENUM_FROM_STRING_BEGIN__( enum ) oENUM_FROM_STRING_SLOT__( namespace, a ) oENUM_FROM_STRING_SLOT__( namespace, b ) oENUM_FROM_STRING_SLOT__( namespace, c ) oENUM_FROM_STRING_SLOT__( namespace, d ) oENUM_FROM_STRING_SLOT__( namespace, e ) oENUM_FROM_STRING_SLOT__( namespace, f ) oENUM_FROM_STRING_SLOT__( namespace, g ) oENUM_FROM_STRING_END__()
#define oENUM_STRING8( enum, namespace, a, b, c, d, e, f, g, h )       oENUM_FROM_STRING_BEGIN__( enum ) oENUM_FROM_STRING_SLOT__( namespace, a ) oENUM_FROM_STRING_SLOT__( namespace, b ) oENUM_FROM_STRING_SLOT__( namespace, c ) oENUM_FROM_STRING_SLOT__( namespace, d ) oENUM_FROM_STRING_SLOT__( namespace, e ) oENUM_FROM_STRING_SLOT__( namespace, f ) oENUM_FROM_STRING_SLOT__( namespace, g ) oENUM_FROM_STRING_SLOT__( namespace, h ) oENUM_FROM_STRING_END__()
#define oENUM_STRING9( enum, namespace, a, b, c, d, e, f, g, h, i )    oENUM_FROM_STRING_BEGIN__( enum ) oENUM_FROM_STRING_SLOT__( namespace, a ) oENUM_FROM_STRING_SLOT__( namespace, b ) oENUM_FROM_STRING_SLOT__( namespace, c ) oENUM_FROM_STRING_SLOT__( namespace, d ) oENUM_FROM_STRING_SLOT__( namespace, e ) oENUM_FROM_STRING_SLOT__( namespace, f ) oENUM_FROM_STRING_SLOT__( namespace, g ) oENUM_FROM_STRING_SLOT__( namespace, h ) oENUM_FROM_STRING_SLOT__( namespace, i ) oENUM_FROM_STRING_END__()
#define oENUM_STRING10( enum, namespace, a, b, c, d, e, f, g, h, i, j )oENUM_FROM_STRING_BEGIN__( enum ) oENUM_FROM_STRING_SLOT__( namespace, a ) oENUM_FROM_STRING_SLOT__( namespace, b ) oENUM_FROM_STRING_SLOT__( namespace, c ) oENUM_FROM_STRING_SLOT__( namespace, d ) oENUM_FROM_STRING_SLOT__( namespace, e ) oENUM_FROM_STRING_SLOT__( namespace, f ) oENUM_FROM_STRING_SLOT__( namespace, g ) oENUM_FROM_STRING_SLOT__( namespace, h ) oENUM_FROM_STRING_SLOT__( namespace, i ) oENUM_FROM_STRING_SLOT__( namespace, j ) oENUM_FROM_STRING_END__()
#endif
