# This file automatically generated by configure. Do not edit!
TOOLCHAIN := x86-win32-vs9
ALL_TARGETS += libs
ALL_TARGETS += examples
ALL_TARGETS += solution
ifeq ($(MAKECMDGOALS),dist)
DIST_DIR?=vpx-vp8-debug-src-x86-win32mt-vs9-v0.9.6
else
DIST_DIR?=$(DESTDIR)/usr/local
endif
LIBSUBDIR=lib

VERSION_MAJOR=0
VERSION_MINOR=9
VERSION_PATCH=6

CONFIGURE_ARGS=--enable-debug-libs --enable-codec-srcs --enable-install-docs --enable-install-srcs --enable-static-msvcrt --target=x86-win32-vs9
CONFIGURE_ARGS?=--enable-debug-libs --enable-codec-srcs --enable-install-docs --enable-install-srcs --enable-static-msvcrt --target=x86-win32-vs9
